name: Release chrome extension

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: yarn --frozen-lockfile
        working-directory: ./chrome-extension
      - name: Build
        run: yarn run build
        working-directory: ./chrome-extension
      - id: packExtensionDir
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: "./chrome-extension/dist"
          zipFilePath: "./chrome-extension/build/twitter-illustration-chrome-extension.zip"
      - name: Set current datetime as environment variable
        env:
          TZ: "Asia/Tokyo"
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "$CURRENT_DATETIME"
          tag_name: "$CURRENT_DATETIME"
          files: ./chrome-extension/build/twitter-illustration-chrome-extension.zip
