name: Release chrome extension

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: yarn --frozen-lockfile
        working-directory: ./chrome-extension
      - name: Build
        run: yarn run build
        working-directory: ./chrome-extension
      - id: packExtensionDir
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: "./chrome-extension/dist"
          zipFilePath: "./chrome-extension/build/my-extension.zip"
      - uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: "./chrome-extension/build/my-extension.zip"
          crxFilePath: "./chrome-extension/build/my-extension.crx"
          privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }},
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "v1.0"
          tag_name: "v1.0"
          files: ./chrome-extension/build/my-extension.crx
